// const mathslib= require('./functions/math')
// de structureing
const {addfn,subFn} =require('./functions/math')
const lib= require('./functions/data')
const mydata= require('./data/json')
console.log(addfn(3,4))
console.log(subFn(6,4))
console.log(lib.data)
console.log(lib)
// console.log(mydata.name)